name: Documentation
on:
  push:
    branches:
      - master
      - updates
    paths:
      - RELEASE_NOTES.md
      - .github/workflows/docs.yml  
jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.100'
      - name: Restore Tools
        run: dotnet tool restore
      - name: Paket Restore
        run: dotnet paket restore
      - name: Build
        run: dotnet build
      - name: Docs
        run: ./docs.sh