name: CI - Fable

on: 
  push:
    paths-ignore:
    - 'README.md'
    - 'docs/'
  pull_request:
    paths-ignore:
    - 'README.md'
    - 'docs/'
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.100'
    - name: Restore Tools
      run: dotnet tool restore
    - name: Paket Restore
      run: dotnet paket restore
    - name: Build
      run: dotnet fable src/Demo/Fable --outDir bin/Fable
