name: CI - MacOS

on: 
  push:
    paths-ignore:
    - 'README.md'
    - 'docs/'
  pull_request:
    paths-ignore:
    - 'README.md'
    - 'docs/'
    
jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.100'
    - name: Restore Tools
      run: dotnet tool restore
    - name: Paket Restore
      run: dotnet paket restore
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test -l "console;verbosity=normal" --no-build --nologo
